=== caspar/Altova/XMLSpy2015/Examples/ExampleSite/site.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v5 beta 4 U (http://www.xmlspy.com) by Robert Gillis (Altova, Inc.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="main">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dictionaries" minOccurs="0"/>
				<xs:element ref="idref"/>
				<xs:element name="pagetitle" type="xs:string" minOccurs="0"/>
				<xs:element ref="content"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sitedata"/>
	<xs:element name="navigation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="base_url" type="xs:string"/>
				<xs:element ref="menu" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="content">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="pagefragment"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="pagefragment">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="block">
					<xs:attribute name="idref" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="header"/>
	<xs:complexType name="block" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="header"/>
			<xs:element ref="table"/>
			<xs:element ref="list"/>
			<xs:element ref="img"/>
			<xs:element ref="pagefragment"/>
			<xs:element ref="span"/>
			<xs:element ref="para"/>
			<xs:element ref="br"/>
			<xs:element ref="bold"/>
			<xs:element ref="link"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="table">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="tr">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="td">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="block">
											<xs:attribute name="style" type="xs:string"/>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="para" type="inlinetype"/>
	<xs:element name="list">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="listitem" type="block"/>
			</xs:choice>
			<xs:attribute name="line">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="solid"/>
						<xs:enumeration value="dashed"/>
						<xs:enumeration value="dotted"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="img">
		<xs:complexType>
			<xs:attribute name="src" type="xs:anyURI"/>
			<xs:attribute name="style" type="xs:string"/>
			<xs:attribute name="class" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="span" type="inlinetype"/>
	<xs:element name="br"/>
	<xs:element name="link">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:choice>
					<xs:element ref="url"/>
					<xs:element ref="idref"/>
				</xs:choice>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="bold"/>
					<xs:element ref="img"/>
					<xs:element ref="br"/>
					<xs:element ref="span"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="style" type="xs:string"/>
			<xs:attribute name="class" type="xs:string"/>
			<xs:attribute name="target" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="links">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="link_instance">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:ID"/>
							<xs:element name="url" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="images">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="image">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:ID"/>
							<xs:element ref="img"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="blocks">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="block_instance">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:ID"/>
							<xs:element ref="pagefragment"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="menu">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element name="idref" type="xs:IDREF"/>
					<xs:element name="title" type="xs:string"/>
				</xs:sequence>
				<xs:sequence>
					<xs:element name="id" type="xs:ID"/>
					<xs:element name="title" type="xs:string"/>
					<xs:choice>
						<xs:element name="url" type="xs:string"/>
						<xs:element ref="menu" maxOccurs="unbounded"/>
						<xs:element name="link_idref" type="xs:IDREF"/>
					</xs:choice>
				</xs:sequence>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="id" type="xs:ID"/>
	<xs:element name="idref" type="xs:IDREF"/>
	<xs:element name="url" type="xs:string"/>
	<xs:element name="dictionaries">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="blocks"/>
				<xs:element ref="navigation"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="inlinetype" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="span"/>
			<xs:element ref="br"/>
			<xs:element ref="img"/>
			<xs:element ref="link"/>
			<xs:element ref="bold"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="strong" type="inlinetype"/>
	<xs:element name="bold" type="inlinetype"/>
</xs:schema>

=== caspar/Altova/XMLSpy2015/Examples/ExampleSite/block_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v5 beta 2 U (http://www.xmlspy.com) by Robert Gillis (Altova, Inc.) -->
<!DOCTYPE main SYSTEM "examplesite.dtd">
<?altova_sps examplesite.sps?>
<main xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="site.xsd">
	<dictionaries>
   &inc_blocks;
   &inc_navigation;
</dictionaries>
	<idref>blockfile</idref>
	<pagetitle>Block File</pagetitle>
	<content>
		<pagefragment>
			<header>Blocks File</header>
			<para>the Block Files contains reusable page fragments. These fragments can be reference within any page of the site by Including a &lt;pagefragment&gt; tag with an idref which corresponds to the id of the Block_instance.</para>
			<img src="output/images/block_file.gif"/>
			<para>
   	               The following paragraph is defined in the blocks.xml file.
                   </para>
			<pagefragment idref="exampleblock"/>
		</pagefragment>
	</content>
</main>

=== caspar/Altova/XMLSpy2015/Examples/ExampleSite/home.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v5 beta 2 U (http://www.xmlspy.com) by Robert Gillis (Altova, Inc.) -->
<!DOCTYPE dictionaries SYSTEM "examplesite.dtd">
<main xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="site.xsd">
     &inc_dictionaries;
      <idref>welcomepage</idref>
	<pagetitle>welcome</pagetitle>
	<content>
		<pagefragment>
			 <pagefragment idref="welcome"/>
			 <pagefragment idref="sample"/>
		       <pagefragment idref="mysitelogo"/>

			 
			 
		</pagefragment>
	</content>
</main>
